# Nexus Package Manager Configuration

NEX_DB_REPO="nexuslinux-os/nex"
NEX_CACHE_DIR="${HOME}/.cache/nex"
NEX_DB_DIR="${HOME}/.local/share/nex"
NEX_DB_FILE="$NEX_DB_DIR/packages.db"
NEX_GITHUB_API="https://api.github.com"
NEX_KEEP_VERSIONS=3
NEXEDITOR="${EDITOR:-nano}"
NEX_PARALLEL_DOWNLOADS=4
NEX_MANAGED_LIST="$NEX_DB_DIR/nex-managed.list"
NEX_COLOR="auto"
